package com.example.rpcprotocol;

public enum ResponseType {
    OK,
    ERROR,
    UPDATE,
    GET_RACE_ENTRIES_BY_ENGINE_CAPACITY,
    GET_PARTICIPANT_NAME_AND_ENGINE_CAPACITY,
    GET_ALL_TEAM_NAMES,
    GET_ALL_ENGINE_CAPACITIES,
    FIND_RACE_BY_ENGINE_CAPACITY,
    GET_LAST_PARTICIPANT,
    ADD_PARTICIPANT,
    ADD_ENTRY
}
